@baseUrl = http://localhost:3001/persons


### get data
GET {{baseUrl}}

### post data
POST {{baseUrl}}
Content-Type: application/json

{
    "name":"mohit",
    "phoneNumber":"2345"
}


### delete data
DELETE {{baseUrl}}/5e0125de43ca9f0c4725ff99

